<?php

namespace ReservationBundle\Repository;

/**
 * SalutationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalutationRepository extends \Doctrine\ORM\EntityRepository
{
}
