services:

    reservation.form.type.reservation:
        class: ReservationBundle\Form\ReservationType
        arguments:
            user: "@=service('security.token_storage').getToken().getUser()"
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    reservation.validator.unique_nin:
        class: ReservationBundle\Validator\Constraints\UniqueNinValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            user: "@=service('security.token_storage').getToken().getUser()"
        tags:
            - { name: validator.constraint_validator, alias: unique_nin }